### ISSUE TITLE
Tensor alignStride has now effect

### ISSUE THREAD

**Issue by lrannabauer** [SeisSol/yateto#15]
[yateto_issue.tar.gz](https://github.com/SeisSol/yateto/files/4966666/yateto_issue.tar.gz)
The attached example seems to ignore the the alignStride=False setting for a matrix U which is the result of a matrix-matrix product SF:

        F     = Tensor('F' , (SWE_DG_DOFS, 3) )
        S     = Tensor('S' , (SWE_DG_DOFS, SWE_DG_DOFS) )
        U     = Tensor('U' , (SWE_DG_DOFS, 3) ,alignStride=False)

kernel:

        example = U["lq"] <= S["lj"] * F["jq"] 

Resulting libxsmm call:  
libxsmm_m28_n3_k28_ldA28_ldB28_ldC28_alpha1_beta0_alignedA1_**aligned**C1_pfsigonly(S, F, U, nullptr, nu\
llptr, nullptr);

To run the example set the yateto_dir in runExample.sh and run the script.
Thanks

**Comment by uphoffc** [comment]
This issue is addressed in the new_alignment_mode branch (PR is open). Please use this branch and pass alignStride=Alignment.Unaligned to force unaligned memory access.
