### ISSUE TITLE
Constant Folding

### ISSUE THREAD

**Issue by krenzland** [SeisSol/yateto#2]
Constant Folding would be useful.
We already have examples of this, e.g. in neighbor kernel R/M (projection to boundary basis divided by mass matrix).
This wouldn't lead to a performance gain but would easy the implementation of new kernel and would allow reuse of matrices without a performance penalty.

Overall this would be a cheap idea to improve the quality of the code generator.

Some implementation ideas:
- Strength reduction would need to favor grouping of constant matrices over other multiplication orders with same cost.
- A constant folding optimization pass could be introduced that replaces the multiplication of two (or more) constant matrices with a new constant matrix.

**Comment by uphoffc** [comment]
Not quite constant folding, but you may now compute tensors inside yateto using the same language you use to specify the kernels. (As long as the actual values are available.)

See 9eacec5bb474ab7d0b5381bab469fc19dc9df937 and d5e230aee0e31b8be716303a716e40bf510cc11a

Application example:
```python
N = 8
B = Tensor('B', (N, N), numpy.ones((N,N)))
F = Tensor('F', (N, N), numpy.ones((N,N)))
A = tensor_from_constant_expression('A', F['ik'] * B['kj'], targetIndices = 'ji', tensorArgs={'memoryLayoutClass': CSCMemoryLayout})
```
